import * as T from './vendor/three/three.module.js';
import {GLTFLoader} from './vendor/three/addons/loaders/GLTFLoader.js';
import {clone} from './vendor/three/addons/utils/SkeletonUtils.js';
import {OrbitControls} from './vendor/three/addons/controls/OrbitControls.js';

export async function load(K,oldCanvas,walks){
 const renderer=new T.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(1);renderer.domElement.id='world';renderer.domElement.style.cssText='display:block;width:100%;aspect-ratio:3/2;touch-action:none';
 const scene=new T.Scene();scene.background=new T.Color('#9cbbbd');scene.fog=new T.Fog('#9cbbbd',40,90);
 const camera=new T.PerspectiveCamera(42,1.5,.1,150),target=new T.Vector3(0,0,0);
 camera.position.set(0,23,25);camera.lookAt(target);const controls=new OrbitControls(camera,renderer.domElement);controls.target.copy(target);controls.enableDamping=true;controls.minDistance=18;controls.maxDistance=46;controls.minPolarAngle=.2;controls.maxPolarAngle=1.15;controls.maxAzimuthAngle=.65;controls.minAzimuthAngle=-.65;controls.enablePan=false;
 const hemi=new T.HemisphereLight(0xdffaff,0x526337,2.7);scene.add(hemi);const sun=new T.DirectionalLight(0xffe4ab,3.2);sun.position.set(-8,15,10);scene.add(sun);
 const loader=new GLTFLoader();const [environment,terrain,manifest]=await Promise.all([loader.loadAsync('./assets/environment/forest.glb'),fetch('./assets/environment/terrain.json').then(r=>r.json()),fetch('./assets/models/manifest.json').then(r=>r.json())]);scene.add(environment.scene);
 function height(x,z){const fx=T.MathUtils.clamp((x+14)/28*80,0,79.999),fz=T.MathUtils.clamp((z+10)/20*60,0,59.999),ix=Math.floor(fx),iz=Math.floor(fz),tx=fx-ix,tz=fz-iz,h=terrain.heights;return T.MathUtils.lerp(T.MathUtils.lerp(h[iz][ix],h[iz][ix+1],tx),T.MathUtils.lerp(h[iz+1][ix],h[iz+1][ix+1],tx),tz);}
 const point=(x,y,lift=0)=>new T.Vector3((x-600)/50,height((x-600)/50,(y-400)/50)+lift,(y-400)/50);
 const groundMat=new T.MeshStandardMaterial({color:0x32432b,roughness:1});const base=new T.Mesh(new T.BoxGeometry(28,.9,20),groundMat);base.position.y=-1;scene.add(base);
 // Small deterministic ground details keep the reused terrain readable at game scale.
 const grassCanvas=document.createElement('canvas');grassCanvas.width=grassCanvas.height=256;const gc=grassCanvas.getContext('2d');gc.fillStyle='#b9c89e';gc.fillRect(0,0,256,256);for(let i=0;i<3500;i++){const x=(i*73.37)%256,y=(i*37.13)%256;gc.fillStyle=i%2?'#92a67c':'#d0d6a7';gc.fillRect(x,y,1,2);}const grassTexture=new T.CanvasTexture(grassCanvas);grassTexture.wrapS=grassTexture.wrapT=T.RepeatWrapping;grassTexture.repeat.set(12,9);grassTexture.colorSpace=T.SRGBColorSpace;environment.scene.traverse(o=>{if(o.name==='Ground'){o.material.map=grassTexture;o.material.needsUpdate=true;}});
 const leafMat=new T.MeshStandardMaterial({color:0x496d27,roughness:1,flatShading:true}),leafGeo=new T.IcosahedronGeometry(1,1),leaves=new T.InstancedMesh(leafGeo,leafMat,terrain.canopies.length*3),dummy=new T.Object3D();let li=0;
 for(const [x,y,z] of terrain.canopies)for(let j=0;j<3;j++){dummy.position.set(x+Math.sin(j*2.1)*.3,y-.25+j*.15,z+Math.cos(j*2.1)*.3);dummy.scale.set(.7, .5, .65);dummy.updateMatrix();leaves.setMatrixAt(li++,dummy.matrix);}scene.add(leaves);
 const rockGeo=new T.DodecahedronGeometry(.24),rockMat=new T.MeshStandardMaterial({color:0x899183,roughness:1,flatShading:true});const mushrooms=new T.Group();scene.add(mushrooms);const capGeo=new T.SphereGeometry(.19,8,6,0,Math.PI*2,0,Math.PI/2),capMat=new T.MeshStandardMaterial({color:0xcf663c,roughness:.8}),stemGeo=new T.CylinderGeometry(.035,.06,.22,5),stemMat=new T.MeshStandardMaterial({color:0xe5d4a8});
 for(let i=6;i<K.PATH.length-6;i+=6){const p=K.PATH[i],n=K.PATH[i+1],len=Math.hypot(n[0]-p[0],n[1]-p[1]),side=i%12?-1:1,pos=point(p[0]-(n[1]-p[1])/len*37*side,p[1]+(n[0]-p[0])/len*37*side);const rock=new T.Mesh(rockGeo,rockMat);rock.position.copy(pos);rock.scale.set(1+i%3*.2,.55,1);scene.add(rock);if(i%12===0){const cap=new T.Mesh(capGeo,capMat),stem=new T.Mesh(stemGeo,stemMat);cap.position.copy(pos).add(new T.Vector3(.35,.25,.2));stem.position.copy(pos).add(new T.Vector3(.35,.11,.2));mushrooms.add(cap,stem);}}
 const roadMaterial=new T.MeshStandardMaterial({color:0xc0a16a,roughness:1});const vertices=[],indices=[];
 K.PATH.forEach(([x,y],i)=>{const prev=K.PATH[Math.max(0,i-1)],next=K.PATH[Math.min(K.PATH.length-1,i+1)],dx=next[0]-prev[0],dy=next[1]-prev[1],length=Math.hypot(dx,dy);for(const side of [-1,1]){const p=point(x-dy/length*22*side,y+dx/length*22*side,.04);vertices.push(...p);}if(i>0){const n=i*2;indices.push(n-2,n,n-1,n-1,n,n+1);}});
 const roadGeo=new T.BufferGeometry();roadGeo.setAttribute('position',new T.Float32BufferAttribute(vertices,3));roadGeo.setIndex(indices);roadGeo.computeVertexNormals();roadMaterial.side=T.DoubleSide;scene.add(new T.Mesh(roadGeo,roadMaterial));
 const padMat=new T.MeshStandardMaterial({color:0xc5c5a1,roughness:1}),padGeo=new T.CylinderGeometry(.55,.65,.16,16),pads=[];
 function label(text,color='#fff6cf'){const c=document.createElement('canvas');c.width=128;c.height=64;const ctx=c.getContext('2d');ctx.font='bold 42px system-ui';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(text,64,46);const texture=new T.CanvasTexture(c),sprite=new T.Sprite(new T.SpriteMaterial({map:texture,depthTest:false}));sprite.scale.set(.6,.3,1);return sprite;}
 for(let i=0;i<K.PADS.length;i++){const p=K.PADS[i],mesh=new T.Mesh(padGeo,padMat);mesh.position.copy(point(p.x,p.y,.06));scene.add(mesh);const number=label(String(i+1));number.position.copy(point(p.x,p.y,.24));scene.add(number);pads.push({number,p});}
 const shrine=new T.Group(),gold=new T.MeshStandardMaterial({color:0xffca45,metalness:.4,roughness:.35});const pear=new T.Mesh(new T.SphereGeometry(.45,16,12),gold);pear.scale.set(1,1.35,1);pear.position.y=.65;shrine.add(pear);const neck=new T.Mesh(new T.SphereGeometry(.24,12,8),gold);neck.position.set(.03,1.13,0);shrine.add(neck);const stem=new T.Mesh(new T.CylinderGeometry(.035,.05,.3,6),new T.MeshStandardMaterial({color:0x50371b}));stem.position.set(.03,1.42,0);shrine.add(stem);shrine.position.copy(point(...K.PATH.at(-1)));scene.add(shrine);
 const resources={};for(const [name,model] of Object.entries(manifest.models)){const message=document.querySelector('#loading p');if(message)message.textContent='Bringing the 3D forest to life…';resources[name]=await loader.loadAsync('./assets/models/'+model.file);}
 const units=new Map(),effects=new T.Group();scene.add(effects);let prevTime=0,previousStage=0;
 const hpGeo=new T.PlaneGeometry(1,.07),hpBack=new T.MeshBasicMaterial({color:0x182820,depthTest:false}),hpGreen=new T.MeshBasicMaterial({color:0xb9e78d,depthTest:false});
 function unit(entity,tower){const name=tower?entity.type:entity.kind==='brute'?'hulk':['boss','venom'].includes(entity.kind)?entity.kind:'base',id=(tower?'t':'e')+entity.id,signature=name+Boolean(entity.mutated);let u=units.get(id);if(u?.signature===signature)return u;if(u){scene.remove(u.group);u.mixer?.uncacheRoot(u.model);if(u.frames){u.model.material.map.dispose();u.model.material.dispose();}units.delete(id);}
  const group=new T.Group();let model,mixer,animations;
  if(entity.mutated){const frames=walks['mutant-'+name];model=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(frames[0]),transparent:true}));model.scale.set(1.6*entity.size,1.6*entity.size,1);model.position.y=.8*entity.size;group.add(model);u={group,model,frames,frame:-1};}
  else{const asset=resources[name];model=clone(asset.scene);const bounds=new T.Box3().setFromObject(model),size=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3()),scale=(tower?1.65:1.35*entity.size)/size.y;model.scale.setScalar(scale);model.position.set(-center.x*scale,-bounds.min.y*scale,-center.z*scale);group.add(model);mixer=new T.AnimationMixer(model);animations=asset.animations;u={group,model,mixer,animations};}
  if(!tower){const bar=new T.Group(),back=new T.Mesh(hpGeo,hpBack),front=new T.Mesh(hpGeo,hpGreen);bar.add(back,front);bar.position.y=1.6*entity.size;front.position.z=.001;group.add(bar);u.bar=bar;u.hp=front;}
  u.signature=signature;scene.add(group);units.set(id,u);return u;
 }
 const ring=new T.Mesh(new T.RingGeometry(.98,1,64),new T.MeshBasicMaterial({color:0x9ef4e7,transparent:true,opacity:.45,side:T.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;scene.add(ring);
 function render(game,{selectedTower}){
  const dt=Math.max(0,Math.min(.1,game.time-prevTime));prevTime=game.time;
  if(previousStage!==game.stage){previousStage=game.stage;const ash=game.stage===2;scene.background.set(ash?0x50403c:0x9cbbbd);scene.fog.color.copy(scene.background);leaves.visible=!ash;roadMaterial.color.set(ash?0x6e5750:0xc0a16a);environment.scene.traverse(o=>{if(o.name==='Ground')o.material.color.set(ash?0x42382d:0x578131);});sun.color.set(ash?0xff925a:0xffe4ab);}
  const seen=new Set();for(const [list,tower] of [[game.towers,true],[game.enemies,false]])for(const e of list){const id=(tower?'t':'e')+e.id,u=unit(e,tower);seen.add(id);u.group.position.copy(point(e.x,e.y,.06));
   if(!tower){const ahead=K.position(e.progress+3);u.group.rotation.y=Math.atan2(ahead.x-e.x,ahead.y-e.y);u.hp.scale.x=Math.max(.001,e.hp/e.maxHp);u.hp.position.x=-(1-u.hp.scale.x)*.5;u.bar.quaternion.copy(u.group.quaternion).invert().multiply(camera.quaternion);}
   else{u.group.scale.setScalar(1+(e.level-1)*.06);const target=game.enemies.find(v=>Math.hypot(v.x-e.x,v.y-e.y)<K.stats(e).range);if(target)u.group.rotation.y=Math.atan2(target.x-e.x,target.y-e.y);}
   if(u.mixer){const clip=tower?(e.recoil>0?'cast':'idle'):'walk_stopmotion';if(u.clip!==clip){u.mixer.stopAllAction();const a=u.animations.find(a=>a.name.toLowerCase()===clip);if(a)u.mixer.clipAction(a).reset().play();u.clip=clip;u.animationTime=.125;}u.animationTime=(u.animationTime||0)+dt;if(u.animationTime>=.125){u.mixer.update(u.animationTime);u.animationTime=0;}}
   else{const f=Math.floor(e.progress/10+e.id)%4;if(f!==u.frame){u.model.material.map.image=u.frames[f];u.model.material.map.needsUpdate=true;u.frame=f;}}
  }
  for(const [id,u] of units)if(!seen.has(id)){scene.remove(u.group);u.mixer?.uncacheRoot(u.model);if(u.frames){u.model.material.map.dispose();u.model.material.dispose();}units.delete(id);}
  const activeEffects=[...game.projectiles,...game.effects].slice(-70);for(let i=0;i<Math.max(activeEffects.length,effects.children.length);i++){const e=activeEffects[i];let line=effects.children[i];if(!e){line.visible=false;continue;}if(!line){line=new T.Line(new T.BufferGeometry().setAttribute('position',new T.Float32BufferAttribute(new Float32Array(6),3)),new T.LineBasicMaterial({transparent:true,opacity:.8}));line.frustumCulled=false;effects.add(line);}line.visible=true;line.material.color.set(e.color||0xffd98a);const positions=line.geometry.attributes.position;positions.setXYZ(0,...point(e.x,e.y,.65));positions.setXYZ(1,...point(e.tx??e.x,e.ty??e.y,.5));positions.needsUpdate=true;}
  ring.visible=!!selectedTower;if(selectedTower){ring.position.copy(point(selectedTower.x,selectedTower.y,.08));ring.scale.setScalar(K.stats(selectedTower).range/50);}
  controls.update();camera.updateMatrixWorld();for(const [i,{p,number}] of pads.entries()){number.visible=!game.towers.some(t=>t.pad===i);const projected=point(p.x,p.y,.15).project(camera),button=document.querySelector(`[data-pad="${i}"]`);if(button){button.style.left=(projected.x*.5+.5)*100+'%';button.style.top=(-projected.y*.5+.5)*100+'%';}}
  renderer.render(scene,camera);document.documentElement.dataset.battlefield3d='ready';
 }
 oldCanvas.style.display='none';oldCanvas.before(renderer.domElement);new ResizeObserver(()=>{const w=oldCanvas.parentElement.clientWidth;renderer.setSize(w,w*2/3,false);camera.aspect=1.5;camera.updateProjectionMatrix();}).observe(oldCanvas.parentElement);
 const reset=document.createElement('button');reset.textContent='Reset view';reset.style.cssText='width:auto;padding:0 10px;white-space:nowrap';reset.onclick=()=>{camera.position.set(0,23,25);controls.target.copy(target);controls.update();};document.querySelector('.map-controls').append(reset);
 const note=document.createElement('span');note.textContent='Drag to orbit · Scroll to zoom';note.style.cssText='position:absolute;bottom:91px;right:14px;color:#fff7ce;font:11px system-ui;pointer-events:none';oldCanvas.parentElement.append(note);
 return {render};
}
