import * as T from './vendor/three/three.module.js';
import {GLTFLoader} from './vendor/three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from './vendor/three/addons/controls/OrbitControls.js';
const names={lady:'Lady Never Scared',phil:'Phil Heal',reno:'Reno Mo',demon:'Converted Demon',knowme:'KnowME',host:'Host',sailor:'Old Sailor',maahaa:'Maahaa',fordenad:'Fordenand',base:'Cock Nibble',hulk:'Hulk Nemesis',venom:'Venom Nemesis',boss:'King Nibble'};
const $=s=>document.querySelector(s),scene=new T.Scene(),renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));$('#viewport').append(renderer.domElement);
const camera=new T.PerspectiveCamera(35,1,.01,100),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=1;controls.maxDistance=12;scene.add(new T.HemisphereLight(0xffffff,0x4e563c,2.5));const light=new T.DirectionalLight(0xffefd1,3);light.position.set(3,5,6);scene.add(light);
const loader=new GLTFLoader(),cache=new Map();let manifest,active,mixer,paused=false,serial=0,last=performance.now(),size=2;
function reset(){controls.target.set(0,1,0);camera.position.set(.5,1.25,size*2.8);controls.update();}
function action(){if(!mixer)return;mixer.stopAllAction();const clip=active.animations.find(a=>a.name===$('#clip').value);if(clip)mixer.clipAction(clip).reset().play();}
async function select(id){const token=++serial;$('#name').textContent=names[id];$('#status').textContent='Loading model…';$('#clip').disabled=true;document.querySelectorAll('#roster button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===id)));try{
 let asset=cache.get(id);if(!asset){asset=await loader.loadAsync('assets/models/'+manifest.models[id].file);cache.set(id,asset);}if(token!==serial)return;
 if(active){scene.remove(active.group);mixer.stopAllAction();mixer.uncacheRoot(active.scene);}const group=new T.Group();group.add(asset.scene);const bounds=new T.Box3().setFromObject(asset.scene),extent=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3()),scale=2/extent.y;group.scale.setScalar(scale);group.position.set(-center.x*scale,-bounds.min.y*scale,-center.z*scale);scene.add(group);active={...asset,group};mixer=new T.AnimationMixer(asset.scene);size=Math.max(2,extent.x*scale,extent.z*scale);
 $('#clip').replaceChildren(...asset.animations.map(a=>{const o=document.createElement('option');o.value=a.name;o.textContent=a.name==='walk_stopmotion'?'Walk · stop motion':a.name==='cast'?'Cast / action':a.name;return o;}));$('#clip').disabled=false;action();reset();$('#download').href='assets/models/'+manifest.models[id].file;$('#download').download=names[id]+' - Rigged.glb';$('#status').textContent=asset.animations.length+' embedded animations · Drag to rotate · Scroll to zoom';
 }catch(e){if(token===serial)$('#status').textContent='Could not load this model: '+e.message;}}
$('#clip').onchange=action;$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'Play':'Pause';};$('#reset').onclick=reset;
new ResizeObserver(()=>{const w=$('#viewport').clientWidth,h=innerWidth<720?360:480;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}).observe($('#viewport'));
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(!paused&&!document.hidden)mixer?.update(dt*Number($('#speed').value));controls.update();renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);
try{const r=await fetch('assets/models/manifest.json');if(!r.ok)throw Error('Manifest unavailable');manifest=await r.json();for(const [id,name] of Object.entries(names)){if(!manifest.models[id])continue;const b=document.createElement('button');b.textContent=name;b.dataset.id=id;b.onclick=()=>select(id);$('#roster').append(b);}await select('lady');}catch(e){$('#status').textContent=e.message;}
for(const id of ['knowme','host','sailor','maahaa','fordenad','lady','phil','reno']){const card=document.createElement('article');card.className='gif-card';const h=document.createElement('h3');h.textContent=names[id];const im=new Image();im.src='assets/celebration/'+id+'.gif';im.alt=names[id]+' existing motion sprite';im.loading='lazy';const a=document.createElement('a');a.href=im.src;a.download=names[id]+'.gif';a.textContent='Download existing GIF';card.append(h,im,a);$('#gifs').append(card);}
const actionNames={lady:'Lady · Healing magic',phil:'Phil · Shadow uppercut',reno:'Reno · Thorn magic','demon-action':'Demon · Battle magic',base:'Cock Nibble · Five-pose walk',hulk:'Hulk · Five-pose walk',venom:'Venom · Five-pose walk',boss:'King Nibble · Five-pose walk',demon:'Demon · Five-pose walk'};
const actionManifest=await fetch('assets/actions/manifest.json').then(r=>r.json());
for(const [id,name] of Object.entries(actionNames)){const card=document.createElement('article');card.className='gif-card';const h=document.createElement('h3');h.textContent=name;const im=new Image();im.src='assets/actions/'+actionManifest.gifs[id].file;im.alt=name;im.loading='lazy';const a=document.createElement('a');a.href=im.src;a.download=name+'.gif';a.textContent='Download new GIF';card.append(h,im,a);$('#actions').append(card);}
