(function(){
  'use strict';
  const K=window.KnollDefense, game=new K.Game(), canvas=document.querySelector('#game'), ctx=canvas.getContext('2d');
  const $=s=>document.querySelector(s), imgs={};
  const art={knowme:'assets/knowme.webp',host:'assets/host.webp',sailor:'assets/sailor.webp',maahaa:'assets/maahaa.webp',fordenad:'assets/fordenad.webp',lady:'assets/lady.png',phil:'assets/phil.png',reno:'assets/reno.png',board:'assets/forest-expanded.webp',burnt:'assets/forest-burnt.webp'}; 
  const cards=[['knowme','1'],['host','2'],['sailor','3'],['maahaa','4'],['fordenad','5'],['lady','6'],['phil','7']]; let selected='knowme', selectedTower=null, placing=false, paused=false, speed=1, last=0, raf=0, toastTimer=0, sound=false;
  const sfx=new KnollAudio(),walks={};let visualTime=0,models3d,battlefield;
  let ready=false;
  const roman=['','I','II','III'];
  function loadAssets(){return Promise.all(Object.entries(art).map(async([k,src])=>{imgs[k]=await new Promise(resolve=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>resolve(null);im.src=src;});}));}
  async function loadWalks(){await Promise.all(['base','hulk','venom','boss'].flatMap(kind=>['walk','mutant'].map(async prefix=>{walks[prefix+'-'+kind]=await loadWalkSheet('assets/'+prefix+'-'+kind+'.webp');})));}
  function makeRoster(){
    $('#roster').innerHTML=cards.map(([type,key])=>{const t=K.TYPES[type];return `<button class="tower-card" data-type="${type}"><div class="card-art"><img src="${art[type]}" alt="${t.name} gnome"><span class="card-key">${key}</span></div><div class="card-copy"><strong>${t.name}</strong><small>${t.power}</small><span class="card-cost">✧ ${t.cost}<em>+</em></span></div></button>`}).join('');
    document.querySelectorAll('.tower-card').forEach(b=>b.onclick=()=>selectType(b.dataset.type));
  }
  function selectType(type){if((K.TYPES[type].unlock||1)>game.stage){toast('Unlocks in Level '+K.TYPES[type].unlock);return;}selected=type;selectedTower=null;placing=true;document.querySelectorAll('.tower-card').forEach(b=>b.classList.toggle('selected',b.dataset.type===type));updateInspector();paint();}
  function setTower(t){selectedTower=t;placing=false;selected=t.type;document.querySelectorAll('.tower-card').forEach(b=>b.classList.toggle('selected',b.dataset.type===selected));updateInspector();paint();}
  function updateInspector(){const t=selectedTower, type=t?t.type:selected, d=K.TYPES[type], s=t?K.stats(t):{damage:d.damage,range:d.range,interval:d.interval};$('#inspectorEyebrow').textContent=t?'PLACED GUARDIAN':'MEET YOUR GUARDIAN';$('#levelLabel').textContent=t?roman[t.level]:'I';$('#towerName').textContent=d.name;$('#towerTitle').textContent=d.title.toUpperCase();$('#towerDescription').textContent=d.description;$('#powerBadge').textContent=d.power.toUpperCase();$('#portraitImage').src=art[type];$('#portraitImage').alt=d.name+' guardian';$('#damageStat').textContent=Math.round(s.damage);$('#rangeStat').textContent=Math.round(s.range);$('#rateStat').textContent=(1/s.interval).toFixed(1)+'/s';$('#towerExtra').hidden=!t;$('#killStat').textContent=t?`${t.kills} takedowns · ${Math.ceil(t.hp)}/${t.maxHp} HP`:'';$('#targetBtn').textContent=t?`Target: ${t.targetMode} ↔`:'';$('#actionBtn').hidden=!!t;$('#sellBtn').hidden=!t;$('#sellBtn').textContent=t?`Dismiss guardian · recover ✧ ${Math.floor(t.spent*.7)}`:'';$('#placementNote').textContent=t?'Select a placed guardian to inspect or upgrade.':`Then choose an empty grassy knoll · ✧ ${d.cost}`;if(t){const up=K.upgradeCost(t);$('#actionBtn').hidden=false;$('#actionBtn').innerHTML=t.level<3?`Upgrade to ${roman[t.level+1]} <span>✧ ${up}</span>`:'Fully upgraded';$('#actionBtn').disabled=t.level>=3||game.gold<up;$('#actionBtn').dataset.action='upgrade';}else{$('#actionBtn').hidden=false;$('#actionBtn').disabled=game.gold<d.cost;$('#actionBtn').innerHTML=`Recruit guardian <span>✧ ${d.cost}</span>`;$('#actionBtn').dataset.action='recruit';}}
  function makePads(){const wrap=$('#pads');wrap.innerHTML=K.PADS.map((p,i)=>`<button class="pad" data-pad="${i}" aria-label="Grassy knoll ${i+1}"></button>`).join('');wrap.querySelectorAll('.pad').forEach((b,i)=>b.onclick=()=>{const t=game.towers.find(x=>x.pad===i);if(t){setTower(t);return}if(!placing){toast('Choose a guardian first.');return}const placed=game.place(selected,i);if(!placed)toast(game.gold<K.TYPES[selected].cost?'Not enough gold yet.':'That clearing is unavailable.');else{toast(`${K.TYPES[selected].name} took the clearing.`);selectedTower=placed;placing=false;updateInspector();}refreshPads();paint();});refreshPads();}
  function refreshPads(){document.querySelectorAll('.pad').forEach((b,i)=>{const t=game.towers.find(x=>x.pad===i),p=K.PADS[i];if(!battlefield){b.style.left=(p.x/12)+'%';b.style.top=(p.y/8)+'%';}b.classList.toggle('occupied',!!t);b.title=t?`${K.TYPES[t.type].name} · level ${t.level}`:`Build on clearing ${i+1}`});}
  function drawMap(){ctx.drawImage(game.stage===2?imgs.burnt:imgs.board,0,0,1200,800);if(game.stage===2)drawFlames();}
  function drawFlames(){ctx.save();ctx.globalCompositeOperation='screen';for(let i=1;i<K.PATH.length-1;i+=2){const p=K.PATH[i],n=K.PATH[i+1],len=Math.hypot(n[0]-p[0],n[1]-p[1]);for(const side of [-1,1]){const x=p[0]-(n[1]-p[1])/len*48*side,y=p[1]+(n[0]-p[0])/len*48*side;for(let j=0;j<3;j++){const phase=visualTime*5+i+j*2,height=20+12*Math.sin(phase);ctx.fillStyle=j===2?'#ffe9a9bb':j===1?'#ffad3199':'#fa431766';ctx.beginPath();ctx.moveTo(x-9+j*2,y);ctx.quadraticCurveTo(x-16+Math.sin(phase)*7,y-height*.6,x+Math.sin(phase)*9,y-height-12);ctx.quadraticCurveTo(x+16,y-height*.4,x+9-j*2,y);ctx.fill();}}}ctx.restore();}
  function pathStroke(){ctx.beginPath();ctx.moveTo(...K.PATH[0]);for(const p of K.PATH.slice(1))ctx.lineTo(...p);}
  function drawPads(){for(let i=0;i<K.PADS.length;i++){const p=K.PADS[i],t=game.towers.find(x=>x.pad===i);if(t)continue;ctx.fillStyle='rgba(210,225,168,.35)';ctx.beginPath();ctx.ellipse(p.x,p.y,31,19,0,0,7);ctx.fill();ctx.strokeStyle='rgba(56,82,50,.65)';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#d8ddbd';ctx.font='700 11px Segoe UI';ctx.textAlign='center';ctx.fillText(String(i+1),p.x,p.y+4);ctx.textAlign='left';}}
  function sprite(im,x,y,w,h,alpha=1){if(!im)return;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(im,x-w/2,y-h,w,h);ctx.restore()}
  function drawTowers(towers=game.towers){for(const t of towers){
    const d=K.TYPES[t.type],scale=1+(t.level-1)*.06,clock=game.time+t.id,bob=t.type==='host'?Math.sin(clock*3)*4:Math.sin(clock*2)*1.5;
    ctx.fillStyle='#162f1e55';ctx.beginPath();ctx.ellipse(t.x,t.y+2,33,11,0,0,7);ctx.fill();
    const pose=models3d?.frame(t.type,t.recoil>0?'cast':'idle',clock);sprite(pose||imgs[t.type],t.x-(t.type==='sailor'?t.recoil*7:0),t.y-bob,pose?160*scale:105*scale,pose?160*scale:145*scale);
    ctx.save();ctx.strokeStyle=d.color;ctx.fillStyle=d.color;ctx.shadowColor=d.color;ctx.shadowBlur=12;ctx.globalAlpha=.55;
    if(t.type==='knowme'){for(let i=0;i<6;i++){const a=clock+i*1.05;ctx.beginPath();ctx.arc(t.x+Math.cos(a)*32,t.y-55+Math.sin(a)*18,2+i%2,0,7);ctx.fill();}}
    if(t.type==='host'){ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(t.x,t.y-65,42,13,Math.sin(clock)*.4,0,Math.PI*2);ctx.stroke();}
    if(t.type==='maahaa'){ctx.translate(t.x+17,t.y-120*scale);ctx.rotate(clock*.5);for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.beginPath();ctx.moveTo(9,0);ctx.lineTo(18+t.recoil*12,0);ctx.stroke();}}
    if(t.type==='fordenad'){for(let i=0;i<4;i++){const a=clock*.7+i*Math.PI/2;ctx.save();ctx.translate(t.x+Math.cos(a)*27,t.y-20+Math.sin(a)*9);ctx.rotate(a);ctx.beginPath();ctx.ellipse(0,0,6,2,0,0,7);ctx.fill();ctx.restore();}}
    if(t.type==='sailor'&&t.recoil>0){ctx.globalAlpha=t.recoil*.5;ctx.fillStyle='#e5dab8';ctx.beginPath();ctx.arc(t.x+32,t.y-73-(1-t.recoil)*20,4+(1-t.recoil)*12,0,7);ctx.fill();}
    ctx.restore();ctx.fillStyle=d.color;ctx.font='bold 12px Georgia';ctx.textAlign='center';ctx.fillText(roman[t.level],t.x,t.y+18);ctx.textAlign='left';
  }}

  function drawEnemies(enemies=game.enemies){for(const e of enemies){const kind=e.kind==='brute'?'hulk':['boss','venom'].includes(e.kind)?e.kind:'base',frames=walks[(e.mutated?'mutant':'walk')+'-'+kind],pose=!e.mutated&&models3d?.frame(kind,'walk_stopmotion',game.time+e.id),im=pose||frames[Math.floor(e.progress/10+e.id)%4],h=(pose?125:105)*e.size,w=h*im.width/im.height,bob=0;ctx.fillStyle='#10221966';ctx.beginPath();ctx.ellipse(e.x,e.y+2,w*.35,8,0,0,7);ctx.fill();ctx.save();ctx.translate(e.x,e.y);if(e.direction<0)ctx.scale(-1,1);sprite(im,0,bob,w,h);ctx.restore();ctx.fillStyle='#182820';ctx.fillRect(e.x-22,e.y-h-5,44,4);ctx.fillStyle=e.enraged?'#ff834d':e.kind==='venom'?'#8dff91':e.kind==='boss'?'#ffd569':'#c5e98f';ctx.fillRect(e.x-22,e.y-h-5,44*Math.max(0,e.hp/e.maxHp),4);if(e.slowUntil>game.time||e.poisonUntil>game.time){ctx.strokeStyle=e.poisonUntil>game.time?'#9ff46c':'#8ffff2';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(e.x,e.y,24,8,0,0,7);ctx.stroke();}}}
  function drawEffects(){for(const e of game.effects){const q=Math.max(0,1-e.age/e.life);ctx.save();ctx.globalAlpha=q;ctx.shadowColor=e.color;ctx.shadowBlur=16;
    if(e.kind==='spores'){for(let i=0;i<10;i++){const a=i*.63+e.age*1.9,r=(e.radius||62)*(.35+(i%3)*.12),x=e.x+Math.cos(a)*r*(1-q*.25),y=e.y+Math.sin(a)*r*.55-e.age*14-(i%2)*8;ctx.fillStyle=i%2?'#c9ffff':'#80dcd5';ctx.beginPath();ctx.arc(x,y,2+(i%3),0,7);ctx.fill();}}
    else if(e.kind==='cannon'){const r=(e.radius||80)*(1-q);ctx.strokeStyle='#ffd58a';ctx.lineWidth=7;ctx.beginPath();ctx.arc(e.x,e.y,r,0,7);ctx.stroke();ctx.strokeStyle='#f6a35d';ctx.lineWidth=2;for(let i=0;i<8;i++){const a=i*Math.PI/4+e.age*2;ctx.beginPath();ctx.moveTo(e.x+Math.cos(a)*r*.3,e.y+Math.sin(a)*r*.3);ctx.lineTo(e.x+Math.cos(a)*r,e.y+Math.sin(a)*r);ctx.stroke();}}
    else if(e.kind==='thorns'){ctx.strokeStyle=e.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(e.x,e.y,18+28*(1-q),0,7);ctx.stroke();for(let i=0;i<4;i++){const a=i*1.57+e.age*2;ctx.beginPath();ctx.moveTo(e.x+Math.cos(a)*7,e.y+Math.sin(a)*7);ctx.lineTo(e.x+Math.cos(a)*34,e.y+Math.sin(a)*34);ctx.stroke();}}
    else if(e.kind==='burst'){ctx.strokeStyle=e.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(e.x,e.y,25*(1-q*.4),0,7);ctx.stroke();}
    else if(e.kind==='lightning'){ctx.strokeStyle=e.color;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(e.x,e.y);for(let i=1;i<5;i++){const t=i/5;ctx.lineTo(e.x+(e.tx-e.x)*t+Math.sin(i*8+(e.seed||0))*10,e.y+(e.ty-e.y)*t+Math.cos(i*7+(e.seed||0))*8);}ctx.lineTo(e.tx,e.ty);ctx.stroke();}
    else if(e.kind==='beam'){for(let i=0;i<3;i++){ctx.strokeStyle=i===1?'#fff8c9':e.color;ctx.lineWidth=i===1?5:2;ctx.beginPath();ctx.moveTo(e.x+i*3,e.y);ctx.lineTo(e.tx-i*3,e.ty);ctx.stroke();}ctx.fillStyle='#fffbd0';ctx.beginPath();ctx.arc(e.tx,e.ty,8+q*5,0,7);ctx.fill();}
    else if(e.kind==='muzzle'){ctx.strokeStyle='#ffe8a2';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(e.x,e.y);ctx.lineTo(e.x+(e.tx-e.x)*.18,e.y+(e.ty-e.y)*.18);ctx.stroke();}
    ctx.restore();}}
  function paint(){if(battlefield){battlefield.render(game,{selectedTower});return;}ctx.clearRect(0,0,1200,800);drawMap();drawPads();
    if(selectedTower){const t=selectedTower;ctx.save();ctx.strokeStyle=K.TYPES[t.type].color;ctx.fillStyle=K.TYPES[t.type].color+'12';ctx.setLineDash([5,7]);ctx.beginPath();ctx.arc(t.x,t.y,K.stats(t).range,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();}
    [...game.towers.map(t=>({y:t.y,draw:()=>drawTowers([t])})),...game.enemies.map(e=>({y:e.y,draw:()=>drawEnemies([e])}))].sort((a,b)=>a.y-b.y).forEach(s=>s.draw());
    for(const p of game.projectiles){const q=p.age/p.duration,x=p.x+(p.tx-p.x)*q,y=p.y+(p.ty-p.y)*q-(p.kind==='sailor'?Math.sin(q*Math.PI)*65:0);ctx.save();ctx.translate(x,y);ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=12;
      if(p.kind==='fordenad'){ctx.rotate(Math.atan2(p.ty-p.y,p.tx-p.x));ctx.beginPath();ctx.moveTo(10,0);ctx.lineTo(-8,-4);ctx.lineTo(-4,0);ctx.lineTo(-8,4);ctx.closePath();ctx.fill();}
      else if(p.kind==='knowme'){for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(Math.cos(q*12+i*2.1)*7,Math.sin(q*12+i*2.1)*7,3,0,7);ctx.fill();}}
      else{ctx.fillStyle='#39291d';ctx.beginPath();ctx.arc(0,0,7,0,7);ctx.fill();ctx.strokeStyle='#ffc676';ctx.stroke();}ctx.restore();
    }drawEffects();
  }
  function updateUI(){
    const freezeLeft=Math.max(0,game.freezeUntil-game.time);$('#freezeBtn').hidden=false;$('#freezeBtn').disabled=paused||game.status!=='wave'||game.freezeUsed||!!game.ultimate||!game.towers.some(t=>t.type==='knowme')||!game.enemies.some(e=>e.hp>0&&e.x>=0&&e.x<=K.WIDTH);$('#freezeBtn').textContent=freezeLeft>0?'Deep Freeze · '+freezeLeft.toFixed(1)+'s':game.freezeUsed?'Deep Freeze · USED':'KnowME Deep Freeze · 5s · Once per chapter';
    $('#waveMax').textContent=K.stageWaves(game.stage);document.querySelectorAll('.tower-card').forEach(b=>{b.disabled=(K.TYPES[b.dataset.type].unlock||1)>game.stage;});$('#renoBtn').disabled=paused||game.status!=='wave'||game.gold<1500||!!game.ultimate||game.ultimateCooldown>0||!game.enemies.some(e=>e.hp>0&&e.x>=0&&e.x<=K.WIDTH);$('#renoBtn').textContent=game.ultimate?'Reno Mo · UNLEASHED':game.ultimateCooldown>0?'Reno Mo · '+Math.ceil(game.ultimateCooldown)+'s':'Summon Reno Mo · ✧ 1500';
    if(selectedTower&&!game.towers.includes(selectedTower)){selectedTower=null;updateInspector();}const t=selectedTower,next=Math.min(K.stageWaves(game.stage),game.wave+1),plan=K.wavePlan(next,game.stage);
    $('#actionBtn').disabled=t?(t.level>=3||game.gold<K.upgradeCost(t)):game.gold<K.TYPES[selected].cost;if(t)$('#killStat').textContent=t.kills+' takedowns · '+Math.ceil(t.hp)+'/'+t.maxHp+' HP';
    $('#gold').textContent=game.gold;$('#lives').textContent=game.lives;$('#wave').textContent=game.wave;$('#waveCounter').textContent=String(next).padStart(2,'0')+' / '+K.stageWaves(game.stage);$('#bestRecord').textContent='LEVEL '+game.stage+' / 3';
    $('.map-number').textContent='0'+game.stage;$('.map-header h2').textContent=game.stage===3?'The Eclipse Citadel':game.stage===2?'The Ashen Knoll':'Forest Knoll';document.body.classList.toggle('ashen',game.stage===2);document.body.classList.toggle('eclipse',game.stage===3);
    $('#phase').textContent=game.status==='wave'?'WAVE '+game.wave+' IN PROGRESS':game.status==='lost'?'SHRINE FALLEN':game.status==='won'?'CAMPAIGN COMPLETE':'PREPARE YOUR DEFENSE';
    $('#mapHint').textContent=placing?'Choose a clearing for '+K.TYPES[selected].name:game.stage===2?'The forest burns. The mutants march. Hold the pear.':'Choose a guardian. Claim a clearing. Hold the line.';
    $('#enemyCount').textContent=game.status==='wave'?game.enemies.length+' on the trail':game.lastClear?'Wave '+game.lastClear.wave+' cleared · +'+game.lastClear.bonus+' gold':'Build before they arrive';
    $('#waveProgress').style.width=game.status==='wave'?Math.min(100,game.waveTime/(K.wavePlan(game.wave,game.stage).at(-1).at+8)*100)+'%':'0%';
    $('#waveName').textContent=next===K.stageWaves(game.stage)?'The final reckoning':plan.some(e=>e.kind==='boss')?'A crowned menace':'Flock '+next;
    $('#waveComposition').textContent=plan.length+(game.stage>=2?' mutated enemies':' enemies')+(plan.some(e=>e.kind==='boss')?' · BOSS':'');
    $('#waveDescription').textContent=game.stage===1?'15 waves. Poison arrives in wave 5 and damages towers. Replace fallen guardians.':game.stage===2?'18 waves. Lady heals neighboring towers and converts mutants. Fresh board; your gold carries over.':'20 waves. Phil launches serialized shadow strikes. Save 1500 gold for Reno Mo.';
    $('#waveBtn').disabled=game.status!=='build';const label=game.status==='won'?'Campaign complete ✦':'Send wave '+next+' →';if($('#waveBtn').textContent!==label)$('#waveBtn').textContent=label;refreshPads();
  }
  function toast(s){const el=$('#toast');el.textContent=s;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
  $('#freezeBtn').onclick=()=>{if(!paused&&game.freezeKnowME())toast('KnowME — FIVE-SECOND DEEP FREEZE');};
  $('#renoBtn').onclick=()=>{if(!paused&&game.summonReno())toast('Reno Mo — THORN RECKONING');};
  function handleEvents(){for(const e of game.events.splice(0)){if(e.type==='towerDestroyed')toast(K.TYPES[e.tower.type].name+' fell! Recruit a replacement.');if(e.type==='conversionStart'||e.type==='converted')sfx.play('lady');if(e.type==='ultimateStart')sfx.play('reno');if(e.type==='cast'){sfx.play(e.power)}if(e.type==='stage'){toast('New chapter · +250 gold added');selectedTower=null;placing=false;updateInspector();refreshPads();KnollVictory.show({stage:e.completedStage||game.stage-1,gold:game.gold});}if(e.type==='upgraded'){game.effects.push({kind:'cannon',x:e.tower.x,y:e.tower.y-75,radius:38,color:K.TYPES[e.tower.type].color,life:.7,age:0});toast(`${K.TYPES[e.tower.type].name} reached level ${e.tower.level}.`)}if(e.type==='cleared'){toast(`Wave cleared · +✧ ${e.bonus}${e.milestone?' · milestone +'+e.milestone+' included':''}${e.perfect?' · flawless':''}`)}if(e.type==='leak')toast(`A bird reached the pear · shrine −${e.amount}`);if(e.type==='won')KnollVictory.show({stage:game.stage,gold:game.gold,final:true,onContinue:()=>end('won')});if(e.type==='lost')end('lost')}}
  function end(kind){window.dispatchEvent(new CustomEvent('knoll-run-ended',{detail:{kills:game.kills,stage:game.stage,wave:game.wave,won:kind==='won'}}));$('#endEyebrow').textContent=kind==='won'?'THE KNOLL HOLDS':'THE REALM FELL';$('#endTitle').textContent=kind==='won'?'A legendary little victory.':'The pear has fallen.';$('#endDescription').textContent=kind==='won'?'King Nibble has been sent home. All three stages are cleared. The pear endured 53 waves.':'The flock got through. Gather the guardians and try a new formation.';$('#endStats').innerHTML=`${game.kills} birds defeated <br>${game.gold} gold banked <br>Level ${game.stage} · Wave ${game.wave} of ${K.stageWaves(game.stage)}`;$('#endDialog').showModal()}
  function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(document.hidden){raf=requestAnimationFrame(loop);return;}if(!paused&&!document.querySelector('dialog[open]')){visualTime+=dt;for(let i=0;i<(game.ultimate?1:speed);i++)game.update(dt);}try{paint();updateUI();handleEvents();raf=requestAnimationFrame(loop);}catch(error){showFailure(error);}}
  $('#waveBtn').addEventListener('click',()=>{if(game.startWave()){toast(`Wave ${game.wave} incoming.`);updateUI()}});$('#pauseBtn').addEventListener('click',()=>togglePause());$('#resumeBtn').addEventListener('click',()=>togglePause());$('#speedBtn').addEventListener('click',()=>{speed=speed===1?2:1;$('#speedBtn').textContent=speed+'×';toast(speed===2?'Double-time defense.':'Back to steady hands.')});$('#actionBtn').addEventListener('click',()=>{if(selectedTower){const d=K.TYPES[selectedTower.type];if(game.upgrade(selectedTower.id))toast(`${d.name} upgraded to ${roman[selectedTower.level]}.`);else toast('Not enough gold or already maxed.');updateInspector();updateUI();}else selectType(selected)});$('#sellBtn').addEventListener('click',()=>{if(selectedTower){game.sell(selectedTower.id);selectedTower=null;updateInspector();toast('Guardian dismissed.');}});$('#targetBtn').addEventListener('click',()=>{if(selectedTower){selectedTower.targetMode=selectedTower.targetMode==='first'?'strongest':'first';updateInspector()}});
  function togglePause(){paused=!paused;$('#pauseOverlay').hidden=!paused;$('#pauseBtn').textContent=paused?'▶':'Ⅱ'}
  $('#helpBtn').onclick=()=>$('#helpDialog').showModal();$('#closeHelp').onclick=()=>$('#helpDialog').close();$('#readyBtn').onclick=()=>$('#helpDialog').close();$('#restartBtn').onclick=()=>{$('#endDialog').close();game.reset();paused=false;$('#pauseOverlay').hidden=true;$('#pauseBtn').textContent='Ⅱ';selectedTower=null;selectType('knowme');speed=1;$('#speedBtn').textContent='1×';toast('The knoll is yours to defend.')};$('#soundBtn').onclick=async()=>{sound=!sound;$('#soundBtn').setAttribute('aria-pressed',sound);$('#soundBtn').setAttribute('aria-label',sound?'Mute sound':'Enable sound');$('#soundBtn').textContent=sound?'🔊':'♫';if(sound){try{await sfx.enable();if(!sound)sfx.mute();else toast('Magic sound effects enabled.');}catch{sound=false;sfx.mute();$('#soundBtn').setAttribute('aria-pressed','false');$('#soundBtn').textContent='♫';toast('Audio could not load. Try again.');}}else sfx.mute();};$('#enterStageBtn').onclick=()=>$('#stageDialog').close();
  document.addEventListener('keydown',e=>{if(e.repeat||document.querySelector('dialog[open]')||['INPUT','TEXTAREA','SELECT','BUTTON'].includes(e.target.tagName))return;if(e.key>='1'&&e.key<='7')selectType(cards[+e.key-1][0]);if(e.code==='Space'){e.preventDefault();if(game.status==='build')$('#waveBtn').click()}if(e.key.toLowerCase()==='p')togglePause();if(e.key==='Escape'){placing=false;selectedTower=null;updateInspector()}});
  // Never create a GPU context before the player sees the start screen.
  const loading=$('#loading'),safeURL=new URL(location.href);safeURL.searchParams.set('mode','safe');
  loading.innerHTML='<h2>Welcome to the Knoll.</h2><p>Choose your view. Both use the same game rules.</p><button id="start3d" class="primary" style="width:auto">Enter 3D forest →</button><a id="safeStart" style="color:#ffe5a1;margin:20px" href="'+safeURL.href+'">Compatibility view · no 3D graphics required</a>';
  const blocked=['waveBtn','actionBtn','pauseBtn','speedBtn'];blocked.forEach(id=>$('#'+id).disabled=true);
  document.addEventListener('keydown',event=>{if(!ready)event.stopImmediatePropagation();},true);
  function showFailure(error){console.error('Knoll startup/render failure',error);ready=false;paused=true;loading.hidden=false;loading.classList.add('failed');loading.querySelector('h2').textContent='The forest could not render.';loading.querySelector('p').textContent='Try Compatibility view below, or reload to retry 3D. '+(error?.message||'');$('#start3d').hidden=true;}
  async function start(safe){$('#start3d').disabled=true;loading.querySelector('p').textContent=safe?'Preparing compatibility view…':'Loading the 3D forest and guardians… Compatibility view is available below if loading stalls.';try{
    if(safe){await loadAssets();const view=await import('./compatibility-view.js');battlefield=view.load(K,canvas,imgs);}
    else{const terrain=await import('./battlefield-3d.js');battlefield=await terrain.load(K,canvas,walks);}
    makeRoster();makePads();selectType('knowme');loading.hidden=true;ready=true;blocked.forEach(id=>$('#'+id).disabled=false);paint();updateUI();raf=requestAnimationFrame(loop);
    document.querySelector('#world')?.addEventListener('webglcontextlost',event=>{event.preventDefault();cancelAnimationFrame(raf);showFailure(new Error('The graphics connection was lost.'));});
  }catch(error){showFailure(error);}}
  $('#start3d').onclick=()=>start(false);
  if(new URLSearchParams(location.search).get('mode')==='safe')start(true);
})();
