const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),scope={};for(const f of ['map-layout.js','core.js','campaign.js'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),scope);const K=scope.KnollDefense;
function battle(type='host'){const g=new K.Game();g.stage=3;g.gold=10000;const t=g.place(type,0);t.cooldown=999;g.startWave();g.queue=[];const e=g.spawn('brute');e.progress=500;Object.assign(e,K.position(500));e.speed=0;e.armor=0;return {g,t,e};}
test('Hellfire strikes once for 35% maximum HP and excludes later spawns',()=>{const {g,e}=battle('sailor'),hp=e.hp;assert(g.summonHellfire());assert.equal(g.summonHellfire(),false);const later=g.spawn('boss');later.speed=0;const before=later.hp;for(let i=0;i<16;i++)g.update(.05);assert.equal(e.hp,hp*.65);assert.equal(later.hp,before);});
test('Ford volley delivers exactly 35% maximum HP over five seconds',()=>{const {g,e}=battle('fordenad'),hp=e.hp;assert(g.poisonVolley());assert.equal(g.poisonVolley(),false);for(let i=0;i<115;i++)g.update(.05);assert(Math.abs(e.hp-hp*.65)<1e-7);});
test('Host reverse moves backward for ten seconds and freeze takes priority',()=>{const {g,e}=battle();e.speed=40;assert(g.reverseHost());g.update(.05);assert.equal(e.progress,498);e.frozenUntil=g.time+1;g.update(.05);assert.equal(e.progress,498);g.time=11;g.update(.05);assert(e.progress>498);});
test('two non-overlapping freeze charges per chapter and complete power reset',()=>{const {g,e}=battle('knowme');assert(g.freezeKnowME());assert.equal(g.freezeKnowME(),false);g.time=6;assert(g.freezeKnowME());assert.equal(g.freezeCharges,0);g.time=12;assert.equal(g.freezeKnowME(),false);g.enemies=[];g.wave=20;g.stage=2;g.wave=18;g.reverseUsed=g.volleyUsed=g.hellfireUsed=true;g.update(.05);assert.equal(g.freezeCharges,2);for(const key of ['reverseUsed','volleyUsed','hellfireUsed','cleanseUsed'])assert.equal(g[key],false);});
test('connected Host network extends transitively with diminishing hops',()=>{const {g,t}=battle();g.enemies=[];t.x=100;t.y=100;for(let i=1;i<3;i++){const a=g.place('host',i);a.x=100+i*180;a.y=100;}for(let i=0;i<8;i++){const e=g.spawn('scout');e.x=100+i*100;e.y=100;e.hp=1000;e.armor=0;}g.fire(t,g.enemies[0]);g.enemies.forEach((e,i)=>assert(Math.abs((1000-e.hp)-(i<7?19*Math.pow(.8,i):0))<1e-8));});
test('Lady owns one demon, splashes nearby foes, and never blocks movement',()=>{const {g,t,e}=battle('lady');t.x=e.x;t.y=e.y;g.fire(t,e);g.fire(t,e);assert.equal(g.conversions.length,1);for(let i=0;i<41;i++)g.update(.05);assert.equal(g.allies.length,1);const a=g.allies[0],enemy=g.spawn('boss'),near=g.spawn('scout');for(const v of [enemy,near]){v.progress=a.progress;Object.assign(v,K.position(v.progress));v.hp=10000;v.armor=0;}g.status='wave';const start=enemy.progress,nearHP=near.hp;a.cooldown=0;g.update(.05);assert(enemy.progress>start);assert(near.hp<nearHP);assert.equal(g.target(t),null);assert.equal(K.upgradeCost(t),168);assert.equal(K.TYPES.phil.cost,470);assert.equal(K.upgradeCost({type:'phil',level:1}),441);});
test('Queen schedule, frozen spell clock, disabling and friendly-fire floor',()=>{assert(K.wavePlan(7,3).some(e=>e.kind==='hexqueen'));assert(!K.wavePlan(7,2).some(e=>e.kind==='hexqueen'));const {g,t}=battle();const q=g.spawn('hexqueen');q.x=t.x;q.y=t.y;q.progress=100;q.hexAge=9.99;g.updateQueen(q,.02);assert(t.frozenUntil>g.time);q.frozenUntil=50;const age=q.hexAge;g.updateQueen(q,1);assert.equal(q.hexAge,age);t.frozenUntil=0;g.queenSpell(q,'hex');assert(t.hexUntil>g.time);const friend=g.place('knowme',1);friend.x=t.x;friend.y=t.y;friend.hp=6;for(let i=0;i<20;i++)g.fireFriendly(t);assert.equal(friend.hp,5);assert.equal(g.target(t),null);});
test('new pacing and economy apply once while deliberate 3D tuning remains',()=>{for(const stage of [1,2,3]){const g=new K.Game();g.stage=stage;g.wave=1;const e=g.spawn('scout');assert.equal(e.speed,67*(stage>=2?1.2:1)/1.15);const expected=10*1.25*(stage===2?1.2:1)*1.1,start=g.gold;g.hurt(e,e.hp,null,true);assert(Math.abs(g.gold-start-expected)<1e-8);}assert.equal(K.wavePlan(1)[1].at,(1.13-.035)*1.1*1.15);const g=new K.Game(),t=g.place('knowme',0),before=g.gold;g.sell(t.id);assert.equal(g.gold-before,59);});
