const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),target='C:/Users/rosec/OneDrive/Desktop/KnollKeepers - Final Animation Pack';
const names={knowme:'KnowME',host:'Host',sailor:'Old Sailor',maahaa:'Maahaa',fordenad:'Fordenand',lady:'Lady Never Scared',phil:'Phil Heal',reno:'Reno Mo',base:'Cock Nibble',hulk:'Hulk Nemesis',venom:'Venom Nemesis',boss:'King Nibble',demon:'Converted Demon'};
const m=JSON.parse(fs.readFileSync(path.join(root,'assets/models/manifest.json'))).models,files=[];
for(const [key,name] of Object.entries(names)){files.push([path.join(root,'assets/models',m[key].file),name+' - Rigged.glb']);for(const [dir,label] of [['actions',key==='lady'||key==='phil'||key==='reno'?'3D Action':'5 Pose Walk'],['celebration','Original Action']]){const src=path.join(root,'assets',dir,dir==='actions'&&key==='demon'?'demon-v3.gif':key+'.gif');if(fs.existsSync(src))files.push([src,name+' - '+label+'.gif']);}}
files.push([path.join(root,'assets/actions/demon-action.gif'),'Converted Demon - 3D Action.gif']);
fs.mkdirSync(target,{recursive:true});for(const [,name] of files)if(fs.existsSync(path.join(target,name)))throw Error('Refusing to overwrite '+name);
for(const [src,name] of files){const dest=path.join(target,name);fs.copyFileSync(src,dest);const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');if(sha(src)!==sha(dest))throw Error('Copy mismatch '+name);}
fs.writeFileSync(path.join(target,'START HERE.html'),'<!doctype html><meta charset="utf-8"><title>KnollKeepers Animation Pack</title><h1>KnollKeepers — Final Animation Pack</h1><p>13 rigged models, 9 new five-pose GIFs, and 8 preserved original action GIFs. All files are in this one folder.</p><p><a href="https://metamu.github.io/knollkeepers-3d/character-viewer.html">Open interactive character viewer</a></p><p><a href="https://metamu.github.io/knollkeepers-3d/">Play Knoll Keepers 3D</a></p><p>Chicken rigs use thigh/shin/foot skinning and five held in-place walking poses, not motion capture or terrain-aware foot IK. Earlier files are preserved in the project. New GIF effects are rendered previews, not embedded particle systems in the GLBs. No Hyper3D credits used for this animation pass.</p>');
console.log(JSON.stringify({folder:target,verifiedFiles:files.length,credits:0}));
