const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),scope={};for(const f of ['map-layout.js','core.js','campaign.js'])vm.runInNewContext(fs.readFileSync(path.join(root,f),'utf8'),scope);const K=scope.KnollDefense;
test('browser runtime traverses all 53 waves and emits exactly two chapter wins and final victory',()=>{const g=new K.Game();let waves=0,stages=0;while(g.status!=='won'&&waves<54){const stage=g.stage;assert(g.startWave());waves++;g.queue=[];g.enemies=[];const gold=g.gold;g.update(.05);assert.equal(g.gold,gold+35+(g.wave||K.stageWaves(stage))*5);if(g.stage!==stage){stages++;assert.equal(g.towers.length,0);assert.equal(g.allies.length,0);}}assert.equal(waves,53);assert.equal(stages,2);assert.equal(g.status,'won');assert.equal(g.events.filter(e=>e.type==='won').length,1);});
test('runtime unlocks seven guardians and charges Reno 1500',()=>{const g=new K.Game();g.gold=10000;assert.equal(g.place('lady',0),null);g.stage=2;assert(g.place('lady',0));assert.equal(g.place('phil',1),null);g.stage=3;assert(g.place('phil',1));g.startWave();const e=g.spawn('scout');e.x=10;g.gold=1500;assert(g.summonReno());assert.equal(g.gold,0);});
for(const name of ['lady','phil','reno','demon'])test(name+' runtime GLB has valid bounds, finite data, normalized skin weights and expected clips',()=>{
 const file=fs.readFileSync(path.join(root,'assets/models',name+'.glb')),manifest=JSON.parse(fs.readFileSync(path.join(root,'assets/models/manifest.json'))).models[name];assert.equal(file.readUInt32LE(0),0x46546c67);assert.equal(file.readUInt32LE(8),file.length);assert.equal(crypto.createHash('sha256').update(file).digest('hex'),manifest.sha256);
 const jl=file.readUInt32LE(12),g=JSON.parse(file.toString('utf8',20,20+jl)),bin=file.subarray(28+jl);assert(g.skins.length>0);assert(g.animations.some(a=>a.name==='idle'));assert(g.animations.some(a=>a.name===(name==='demon'?'walk_stopmotion':'cast')));
 const read=index=>{const a=g.accessors[index],v=g.bufferViews[a.bufferView],count={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16}[a.type],size={5121:1,5123:2,5125:4,5126:4}[a.componentType],values=[];for(let i=0;i<a.count;i++)for(let j=0;j<count;j++){const o=(v.byteOffset||0)+(a.byteOffset||0)+i*(v.byteStride||count*size)+j*size;const n=a.componentType===5126?bin.readFloatLE(o):a.componentType===5123?bin.readUInt16LE(o):a.componentType===5121?bin.readUInt8(o):bin.readUInt32LE(o);assert(Number.isFinite(n));values.push(n);}return values;};
 for(const mesh of g.meshes)for(const p of mesh.primitives){const w=read(p.attributes.WEIGHTS_0);for(let i=0;i<w.length;i+=4)assert(Math.abs(w[i]+w[i+1]+w[i+2]+w[i+3]-1)<.001);const pos=read(p.attributes.POSITION);assert(pos.length>0);assert(pos.every(v=>Math.abs(v)<10));}
 for(const a of g.animations){assert(a.channels.length>0);const varying=a.samplers.some(s=>{const v=read(s.output);return v.some((n,i)=>i>3&&Math.abs(n-v[i%4])>.00001);});assert(varying);}
});
