const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const sharp=require('C:/Users/rosec/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=path.resolve(__dirname,'..'),work=path.join(root,'overhaul-workbench/motion-v2'),out=path.join(root,'assets/actions');
const keys=['base','hulk','venom','boss','demon','lady','phil','reno','demon-action'],hash=b=>crypto.createHash('sha256').update(b).digest('hex');
(async()=>{const prepared=[];
 for(const key of keys){const folder=path.join(work,key),receipt=JSON.parse(fs.readFileSync(path.join(folder,'receipt.json'))),frames=[];for(let i=0;i<5;i++)frames.push(await sharp(path.join(folder,`frame-${i}.png`)).ensureAlpha().raw().toBuffer());if(new Set(frames.map(hash)).size!==5)throw Error('Not five distinct rendered poses: '+key);const delay=['lady','phil','reno','demon-action'].includes(key)?240:160;const gif=await sharp(Buffer.concat(frames),{raw:{width:448,height:448*5,channels:4,pageHeight:448}}).gif({loop:0,delay:Array(5).fill(delay),colours:128,dither:.4}).toBuffer();const meta=await sharp(gif,{animated:true}).metadata();if(meta.pages!==5||meta.width!==448||meta.pageHeight!==448)throw Error('Invalid animation '+key);prepared.push({key,gif,receipt,delay,meta});}
 fs.mkdirSync(out,{recursive:true});for(const p of prepared)if(fs.existsSync(path.join(out,p.key+'.gif')))throw Error('Existing GIF '+p.key);
 const manifest=JSON.parse(fs.readFileSync(path.join(root,'assets/models/manifest.json')));const models=[];
 for(const name of keys.slice(0,5)){const filename=name+'-v2.glb',dest=path.join(root,'assets/models',filename);if(fs.existsSync(dest))throw Error('Existing revised model '+name);const bytes=fs.readFileSync(path.join(work,name,filename));const jl=bytes.readUInt32LE(12),g=JSON.parse(bytes.toString('utf8',20,20+jl));if(!g.skins.length||!g.nodes.some(n=>n.name==='shin.L')||!g.nodes.some(n=>n.name==='foot.R'))throw Error('Missing articulation '+name);models.push({name,filename,dest,bytes,g});}
 const gifs={};for(const {key,gif,receipt,delay} of prepared){fs.writeFileSync(path.join(out,key+'.gif'),gif);gifs[key]={file:key+'.gif',frames:5,delayMs:delay,sha256:hash(gif),bytes:gif.length,sourceSha256:receipt.sourceSha256,credits:0};}
 for(const {name,filename,dest,bytes,g} of models){const previous=manifest.models[name];fs.writeFileSync(dest,bytes);manifest.models[name]={...previous,file:filename,previousFile:previous.file,previousSha256:previous.sha256,source:'overhaul-workbench/motion-v2/'+name+'/'+filename,sourceSha256:hash(bytes),sha256:hash(bytes),bytes:bytes.length,clips:g.animations.map(a=>a.name),skins:g.skins.length,walkPoses:5,rig:'articulated thigh/shin/foot, held five-pose in-place walk'};}
 fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify({version:1,kind:'locally rendered 3D stop-motion GIFs',gifs},null,2)+'\n');fs.writeFileSync(path.join(root,'assets/models/manifest.json'),JSON.stringify(manifest,null,2)+'\n');console.log(JSON.stringify({gifs:prepared.length,updatedRigs:models.length,previousGLBsPreserved:true,credits:0}));
})().catch(e=>{console.error(e);process.exitCode=1});
